apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: gateway
