apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gateway
        imagePullPolicy: Never
        env:
          - name: ETCD_ADDR
            value: "etcd:2379"
          - name: REDIS_ADDR
            value: "redis"
        ports:
        - containerPort: 80
